### ISSUE TITLE
Kani crashes when parsing const generics

### ISSUE THREAD

**Issue by agvallejo** [model-checking/kani#1728]
(I'm using Kani version 0.11.0)

Kani seems to crash when encountering const generics (See https://github.com/rust-lang/rfcs/blob/master/text/2000-const-generics.md)

I tried this code:
```rust
struct Foo<const N: usize> {
    field: [u64; N],
}

impl<const N: usize> Foo<N> {
    fn new() -> Self {
        Self { field: [0; N] }
    }
}

fn main() {
    Foo::<32>::new();
    println!("Hello, world!");
}

#[cfg(kani)]
mod proofs {
    use super::*;

    #[kani::proof]
    fn kani_crash() {
        Foo::<32>::new();
    }
}
```

which runs fine on `cargo run` but crashes with a backtrace during code generation on `cargo kani`

This is the backtrace:
```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', kani-compiler/src/codegen_cprover_gotoc/codegen/rvalue.rs:213:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/bc4b39c271bbd36736cbf1c0a1ac23d5df38d365/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/bc4b39c271bbd36736cbf1c0a1ac23d5df38d365/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/bc4b39c271bbd36736cbf1c0a1ac23d5df38d365/library/core/src/panicking.rs:48:5
   3: kani_compiler::codegen_cprover_gotoc::codegen::rvalue::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::codegen_rvalue
   4: kani_compiler::codegen_cprover_gotoc::codegen::statement::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::codegen_statement
   5: kani_compiler::codegen_cprover_gotoc::codegen::block::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::codegen_block
   6: kani_compiler::codegen_cprover_gotoc::codegen::function::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::codegen_function
   7: std::thread::local::LocalKey<T>::with
   8: <kani_compiler::codegen_cprover_gotoc::compiler_interface::GotocCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
   9: <rustc_interface::passes::QueryContext>::enter::<<rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_errors::ErrorGuaranteed>>
  10: <rustc_interface::queries::Queries>::ongoing_codegen
  11: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorGuaranteed>>
  12: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
  13: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>
  14: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>

```

**Comment by tedinski** [comment]
Thank you for the small reproducer. That's awesome. This looks like the same issue as this report:

* https://github.com/model-checking/kani/issues/1662

But let's keep this one open, because that test case that reproduces it is nice, and we should just import that into our test suite when we fix this.
