### ISSUE TITLE
kani-compiler panic on unimplemented scalar

### ISSUE THREAD

**Issue by tedinski** [model-checking/kani#2099]
Reproduction:

```
git clone https://github.com/bitflags/bitflags
cd bitflags
RUST_BACKTRACE=1 cargo kani --enable-unstable --only-codegen assess
```

Result:

```
thread '<unnamed>' panicked at 'not implemented', kani-compiler/src/codegen_cprover_gotoc/codegen/operand.rs:419:18
stack backtrace:
   3: kani_compiler::codegen_cprover_gotoc::codegen::operand::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::codegen_scalar
             at /home/ubuntu/rmc/kani-compiler/src/codegen_cprover_gotoc/codegen/operand.rs:419:18
   4: kani_compiler::codegen_cprover_gotoc::codegen::operand::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::codegen_single_variant_single_field
             at /home/ubuntu/rmc/kani-compiler/src/codegen_cprover_gotoc/codegen/operand.rs:438:22
```

The code in question is a remaining raw `unimplemented` in `codegen_scalar`:

https://github.com/model-checking/kani/blob/5680dac0cb9856001e944095a55702838f8c42fc/kani-compiler/src/codegen_cprover_gotoc/codegen/operand.rs#L419

**Comment by carolynzech** [comment]
The `codegen_scalar` function doesn't exist anymore, and with Kani v0.62.0 at commit https://github.com/bitflags/bitflags/commit/80684fdce62860a73ad2430157fad4273f5891b4 I can clone the repo, add an `extern crate kani` at the top (c.f. https://github.com/model-checking/kani/issues/3906), and run `cargo kani` without issue.
