### ISSUE TITLE
compiler error: `impossible case reached` 

### ISSUE THREAD

**Issue by matthiaskrgr** [model-checking/kani#2500]
I tried this code:

```rust
#[kani::proof]
fn main() {
    match Some(5) {
        None if 1 == 1 && ("T" != "Y" && "T" != "E")  => {}
        _ => {},
    }
}

```

using the following command line invocation:

```
kani file.rs
```

with Kani version:
0.29.0
I expected to see this happen: *explanation*

Instead, this happened: *explanation*
```
error: internal compiler error: compiler/rustc_mir_build/src/thir/pattern/check_match.rs:338:21: impossible case reached

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/f4956053816439a5884cb2ad1247835858f92218/compiler/rustc_errors/src/lib.rs:1643:9
stack backtrace:
   0:     0x7f13fd768cc3 - std::backtrace_rs::backtrace::libunwind::trace::h6dd260ccf76e2a16
                               at /rustc/f4956053816439a5884cb2ad1247835858f92218/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f13fd768cc3 - std::backtrace_rs::backtrace::trace_unsynchronized::h60e795a392c2d181
                               at /rustc/f4956053816439a5884cb2ad1247835858f92218/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f13fd768cc3 - std::sys_common::backtrace::_print_fmt::hb92bc719d8e89e18
                               at /rustc/f4956053816439a5884cb2ad1247835858f92218/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f13fd768cc3 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h433d7296fbd4df36
                               at /rustc/f4956053816439a5884cb2ad1247835858f92218/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f13fd7c9c0f - core::fmt::rt::Argument::fmt::hee863a126433a5fe
                               at /rustc/f4956053816439a5884cb2ad1247835858f92218/library/core/src/fmt/rt.rs:138:9
   5:     0x7f13fd7c9c0f - core::fmt::write::hecf019f127565c17
                               at /rustc/f4956053816439a5884cb2ad1247835858f92218/library/core/src/fmt/mod.rs:1105:21
   6:     0x7f13fd75bd91 - std::io::Write::write_fmt::h4fdee205f020a023
                               at /rustc/f4956053816439a5884cb2ad1247835858f92218/library/std/src/io/mod.rs:1712:15
   7:     0x7f13fd768ad5 - std::sys_common::backtrace::_print::h63f1eb292c01c01d
                               at /rustc/f4956053816439a5884cb2ad1247835858f92218/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f13fd768ad5 - std::sys_common::backtrace::print::h29fa6d106f41082b
                               at /rustc/f4956053816439a5884cb2ad1247835858f92218/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f13fd76b697 - std::panicking::default_hook::{{closure}}::h24c419639c3568dd
  10:     0x7f13fd76b485 - std::panicking::default_hook::hd5faae45a4c2ae6b
                               at /rustc/f4956053816439a5884cb2ad1247835858f92218/library/std/src/panicking.rs:288:9
  11:     0x564ba5b48dfd - kani_compiler::session::PANIC_HOOK::{{closure}}::{{closure}}::h62fc73136c5344f5
  12:     0x7f13fd76bdd5 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h8fd551c79732d109
                               at /rustc/f4956053816439a5884cb2ad1247835858f92218/library/alloc/src/boxed.rs:1976:9
  13:     0x7f13fd76bdd5 - std::panicking::rust_panic_with_hook::hff0f13fd32920cda
                               at /rustc/f4956053816439a5884cb2ad1247835858f92218/library/std/src/panicking.rs:695:13
  14:     0x7f1400f01c81 - std[f87cae68a756700d]::panicking::begin_panic::<rustc_errors[3a653a69f8ba5645]::ExplicitBug>::{closure#0}
  15:     0x7f1400f00ab6 - std[f87cae68a756700d]::sys_common::backtrace::__rust_end_short_backtrace::<std[f87cae68a756700d]::panicking::begin_panic<rustc_errors[3a653a69f8ba5645]::ExplicitBug>::{closure#0}, !>
  16:     0x7f1400ec6466 - std[f87cae68a756700d]::panicking::begin_panic::<rustc_errors[3a653a69f8ba5645]::ExplicitBug>
  17:     0x7f1400f4ac66 - <rustc_errors[3a653a69f8ba5645]::HandlerInner>::bug::<&alloc[ab6e9888d17cae42]::string::String>
  18:     0x7f1400f4a930 - <rustc_errors[3a653a69f8ba5645]::Handler>::bug::<&alloc[ab6e9888d17cae42]::string::String>
  19:     0x7f1400f4517b - rustc_middle[913649502f287e96]::util::bug::opt_span_bug_fmt::<rustc_span[14f600a439c86087]::span_encoding::Span>::{closure#0}
  20:     0x7f1400f42a5a - rustc_middle[913649502f287e96]::ty::context::tls::with_opt::<rustc_middle[913649502f287e96]::util::bug::opt_span_bug_fmt<rustc_span[14f600a439c86087]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  21:     0x7f1400f42a2a - rustc_middle[913649502f287e96]::ty::context::tls::with_context_opt::<rustc_middle[913649502f287e96]::ty::context::tls::with_opt<rustc_middle[913649502f287e96]::util::bug::opt_span_bug_fmt<rustc_span[14f600a439c86087]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  22:     0x7f13fec5350d - rustc_middle[913649502f287e96]::util::bug::bug_fmt
  23:     0x7f13fecef015 - <rustc_mir_build[daad3b5ded865c63]::thir::pattern::check_match::MatchVisitor>::check_let_chain::{closure#0}
  24:     0x7f13fecd41b1 - <rustc_mir_build[daad3b5ded865c63]::thir::pattern::check_match::MatchVisitor as rustc_middle[913649502f287e96]::thir::visit::Visitor>::visit_expr
  25:     0x7f13fecd3b38 - <rustc_mir_build[daad3b5ded865c63]::thir::pattern::check_match::MatchVisitor as rustc_middle[913649502f287e96]::thir::visit::Visitor>::visit_expr
  26:     0x7f13fecd3b38 - <rustc_mir_build[daad3b5ded865c63]::thir::pattern::check_match::MatchVisitor as rustc_middle[913649502f287e96]::thir::visit::Visitor>::visit_expr
  27:     0x7f13fecd45d6 - <rustc_mir_build[daad3b5ded865c63]::thir::pattern::check_match::MatchVisitor as rustc_middle[913649502f287e96]::thir::visit::Visitor>::visit_expr
  28:     0x7f13fecd3b38 - <rustc_mir_build[daad3b5ded865c63]::thir::pattern::check_match::MatchVisitor as rustc_middle[913649502f287e96]::thir::visit::Visitor>::visit_expr
  29:     0x7f13fecd3d64 - <rustc_mir_build[daad3b5ded865c63]::thir::pattern::check_match::MatchVisitor as rustc_middle[913649502f287e96]::thir::visit::Visitor>::visit_expr
  30:     0x7f13fecd3b38 - <rustc_mir_build[daad3b5ded865c63]::thir::pattern::check_match::MatchVisitor as rustc_middle[913649502f287e96]::thir::visit::Visitor>::visit_expr
  31:     0x7f13fecd3b38 - <rustc_mir_build[daad3b5ded865c63]::thir::pattern::check_match::MatchVisitor as rustc_middle[913649502f287e96]::thir::visit::Visitor>::visit_expr
  32:     0x7f13ff9bbede - rustc_mir_build[daad3b5ded865c63]::thir::pattern::check_match::check_match
  33:     0x7f13ff9ba77e - rustc_query_system[1d1bcf182af5b7a6]::query::plumbing::try_execute_query::<rustc_query_impl[7d6e55bf424cf961]::queries::check_match, rustc_query_impl[7d6e55bf424cf961]::plumbing::QueryCtxt>
  34:     0x7f13ff9ddc89 - rustc_mir_build[daad3b5ded865c63]::build::mir_built
  35:     0x7f13ffafabed - rustc_query_system[1d1bcf182af5b7a6]::query::plumbing::try_execute_query::<rustc_query_impl[7d6e55bf424cf961]::queries::mir_built, rustc_query_impl[7d6e55bf424cf961]::plumbing::QueryCtxt>
  36:     0x7f13ffaf0cfa - rustc_mir_transform[9c7d4fb24f1e3cb7]::check_unsafety::unsafety_check_result
  37:     0x7f13ff8ae1ec - rustc_query_system[1d1bcf182af5b7a6]::query::plumbing::try_execute_query::<rustc_query_impl[7d6e55bf424cf961]::queries::unsafety_check_result, rustc_query_impl[7d6e55bf424cf961]::plumbing::QueryCtxt>
  38:     0x7f13ff9c67a4 - rustc_mir_transform[9c7d4fb24f1e3cb7]::mir_const
  39:     0x7f13ff9c577b - rustc_query_system[1d1bcf182af5b7a6]::query::plumbing::try_execute_query::<rustc_query_impl[7d6e55bf424cf961]::queries::mir_const, rustc_query_impl[7d6e55bf424cf961]::plumbing::QueryCtxt>
  40:     0x7f13ff37818d - rustc_mir_transform[9c7d4fb24f1e3cb7]::mir_promoted
  41:     0x7f13ff375f1d - rustc_query_system[1d1bcf182af5b7a6]::query::plumbing::try_execute_query::<rustc_query_impl[7d6e55bf424cf961]::queries::mir_promoted, rustc_query_impl[7d6e55bf424cf961]::plumbing::QueryCtxt>
  42:     0x7f13ff3751e3 - rustc_borrowck[6de7a51b24f88806]::mir_borrowck
  43:     0x7f13ff373a53 - rustc_query_system[1d1bcf182af5b7a6]::query::plumbing::try_execute_query::<rustc_query_impl[7d6e55bf424cf961]::queries::mir_borrowck, rustc_query_impl[7d6e55bf424cf961]::plumbing::QueryCtxt>
  44:     0x7f13ffe479e0 - rustc_data_structures[748554d804d0869f]::sync::par_for_each_in::<&[rustc_span[14f600a439c86087]::def_id::LocalDefId], <rustc_middle[913649502f287e96]::hir::map::Map>::par_body_owners<rustc_interface[bc622c2a0f547140]::passes::analysis::{closure#1}::{closure#0}>::{closure#0}>
  45:     0x7f13ffe41b81 - rustc_interface[bc622c2a0f547140]::passes::analysis
  46:     0x7f14001792a2 - rustc_query_system[1d1bcf182af5b7a6]::query::plumbing::try_execute_query::<rustc_query_impl[7d6e55bf424cf961]::queries::analysis, rustc_query_impl[7d6e55bf424cf961]::plumbing::QueryCtxt>
  47:     0x7f1400178fb0 - <rustc_query_impl[7d6e55bf424cf961]::Queries as rustc_middle[913649502f287e96]::ty::query::QueryEngine>::analysis
  48:     0x7f13ffbe160a - <rustc_middle[913649502f287e96]::ty::context::GlobalCtxt>::enter::<rustc_driver_impl[91ccd4f5692da35d]::run_compiler::{closure#1}::{closure#2}::{closure#4}, core[7ab4a128a7734c10]::result::Result<(), rustc_span[14f600a439c86087]::ErrorGuaranteed>>
  49:     0x7f13ffbe0848 - <rustc_interface[bc622c2a0f547140]::interface::Compiler>::enter::<rustc_driver_impl[91ccd4f5692da35d]::run_compiler::{closure#1}::{closure#2}, core[7ab4a128a7734c10]::result::Result<core[7ab4a128a7734c10]::option::Option<rustc_interface[bc622c2a0f547140]::queries::Linker>, rustc_span[14f600a439c86087]::ErrorGuaranteed>>
  50:     0x7f13ffbde86f - rustc_span[14f600a439c86087]::set_source_map::<core[7ab4a128a7734c10]::result::Result<(), rustc_span[14f600a439c86087]::ErrorGuaranteed>, rustc_interface[bc622c2a0f547140]::interface::run_compiler<core[7ab4a128a7734c10]::result::Result<(), rustc_span[14f600a439c86087]::ErrorGuaranteed>, rustc_driver_impl[91ccd4f5692da35d]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  51:     0x7f13ffbddf00 - std[f87cae68a756700d]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[bc622c2a0f547140]::util::run_in_thread_pool_with_globals<rustc_interface[bc622c2a0f547140]::interface::run_compiler<core[7ab4a128a7734c10]::result::Result<(), rustc_span[14f600a439c86087]::ErrorGuaranteed>, rustc_driver_impl[91ccd4f5692da35d]::run_compiler::{closure#1}>::{closure#0}, core[7ab4a128a7734c10]::result::Result<(), rustc_span[14f600a439c86087]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[7ab4a128a7734c10]::result::Result<(), rustc_span[14f600a439c86087]::ErrorGuaranteed>>
  52:     0x7f13ffbdd821 - <<std[f87cae68a756700d]::thread::Builder>::spawn_unchecked_<rustc_interface[bc622c2a0f547140]::util::run_in_thread_pool_with_globals<rustc_interface[bc622c2a0f547140]::interface::run_compiler<core[7ab4a128a7734c10]::result::Result<(), rustc_span[14f600a439c86087]::ErrorGuaranteed>, rustc_driver_impl[91ccd4f5692da35d]::run_compiler::{closure#1}>::{closure#0}, core[7ab4a128a7734c10]::result::Result<(), rustc_span[14f600a439c86087]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[7ab4a128a7734c10]::result::Result<(), rustc_span[14f600a439c86087]::ErrorGuaranteed>>::{closure#1} as core[7ab4a128a7734c10]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  53:     0x7f13fd776305 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hdbaea59c5dcd35ae
                               at /rustc/f4956053816439a5884cb2ad1247835858f92218/library/alloc/src/boxed.rs:1962:9
  54:     0x7f13fd776305 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hedf781cff528734a
                               at /rustc/f4956053816439a5884cb2ad1247835858f92218/library/alloc/src/boxed.rs:1962:9
  55:     0x7f13fd776305 - std::sys::unix::thread::Thread::new::thread_start::h8db1b8acf05cf216
                               at /rustc/f4956053816439a5884cb2ad1247835858f92218/library/std/src/sys/unix/thread.rs:108:17
  56:     0x7f13fd510bb5 - <unknown>
  57:     0x7f13fd592d90 - <unknown>
  58:                0x0 - <unknown>

Kani unexpectedly panicked during compilation.
Please file an issue here: https://github.com/model-checking/kani/issues/new?labels=bug&template=bug_report.md
error: aborting due to previous error

error: /home/matthias/.kani/kani-0.29.0/bin/kani-compiler exited with status exit status: 101

```

**Comment by matthiaskrgr** [comment]
This looks like it is a crash in rust, are there some special rustc flags that kani uses? I looked at kani -vvvv but nothing stood out for me.

**Comment by zhassan-aws** [comment]
I was able to reproduce this with rustc using the `nightly-2023-04-29` toolchain, which is what Kani currently uses:
```
$ cat iss2500.rs 
fn main() {
    match Some(5) {
        None if 1 == 1 && ("T" != "Y" && "T" != "E")  => {}
        _ => {},
    }
}

$ rustc --version
rustc 1.71.0-nightly (f49560538 2023-04-28)

$ rustc iss2500.rs 
error: internal compiler error: compiler/rustc_mir_build/src/thir/pattern/check_match.rs:338:21: impossible case reached

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/f4956053816439a5884cb2ad1247835858f92218/compiler/rustc_errors/src/lib.rs:1643:9
stack backtrace:
   0:     0x7fd26baf5cc3 - std::backtrace_rs::backtrace::libunwind::trace::h6dd260ccf76e2a16
                               at /rustc/f4956053816439a5884cb2ad1247835858f92218/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fd26baf5cc3 - std::backtrace_rs::backtrace::trace_unsynchronized::h60e795a392c2d181
                               at /rustc/f4956053816439a5884cb2ad1247835858f92218/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
...
```
so might've been an issue with that particular nightly.

**Comment by matthiaskrgr** [comment]
Ah makes sense this is not a kani issue then :)
