### ISSUE TITLE
Concrete playback is broken for harnesses that invoke `any_array`

### ISSUE THREAD

**Issue by celinval** [model-checking/kani#2566]
```rust
#[cfg(kani)]
mod verify {
    use kani::cover;
    type Test = isize;

    #[kani::proof]
    fn try_array() {
        let val: [Test;4] = kani::any();
        kani::cover!(val == [0; 4]);
        kani::cover!(val == [Test::MAX; 4]);
        kani::cover!(val == [Test::MIN; 4]);
    }
}

```

using the following command line invocation:

```
kani -Z concrete-playback --concrete-playback=inplace verify.rs
kani playback verify.rs
```

with Kani version: 0.30.0

I expected to see this happen: Kani should run 3 tests that should succeed.

Instead, this happened: All 3 tests failed because Kani library expected one call to `any_raw` per element of the array.

<details><summary>Playback command output</summary>

```
Executable /tmp/kani_concrete_playback

running 3 tests
test verify::kani_concrete_playback_try_array_6045483812967712144 ... FAILED
test verify::kani_concrete_playback_try_array_16394507256935443288 ... FAILED
test verify::kani_concrete_playback_try_array_16670622316451455477 ... FAILED

failures:

---- verify::kani_concrete_playback_try_array_6045483812967712144 stdout ----
thread 'verify::kani_concrete_playback_try_array_6045483812967712144' panicked at 'Expected 32 bytes instead of 8 bytes in the following det vals vec: [0, 0, 0, 0, 0, 0, 0, 0]', /library/kani/src/concrete_playback.rs:61:62

---- verify::kani_concrete_playback_try_array_16394507256935443288 stdout ----
thread 'verify::kani_concrete_playback_try_array_16394507256935443288' panicked at 'Expected 32 bytes instead of 8 bytes in the following det vals vec: [0, 0, 0, 0, 0, 0, 0, 128]', /library/kani/src/concrete_playback.rs:61:62
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- verify::kani_concrete_playback_try_array_16670622316451455477 stdout ----
thread 'verify::kani_concrete_playback_try_array_16670622316451455477' panicked at 'Expected 32 bytes instead of 8 bytes in the following det vals vec: [255, 255, 255, 255, 255, 255, 255, 127]', /library/kani/src/concrete_playback.rs:61:62

failures:
    verify::kani_concrete_playback_try_array_16394507256935443288
    verify::kani_concrete_playback_try_array_16670622316451455477
    verify::kani_concrete_playback_try_array_6045483812967712144

test result: FAILED. 0 passed; 3 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

error: /tmp/kani_concrete_playback exited with status exit status: 101
```
</details>
I believe this might've been a regression added by #2199

**Comment by carolynzech** [comment]
Verification succeeds in Kani v0.58. I believe #3389 fixed this.
