### ISSUE TITLE
ICE: `missing tokens for node: Expr `

### ISSUE THREAD

**Issue by matthiaskrgr** [model-checking/kani#3446]
I tried this code:

```rust
fn main() {
    #[kani::proof]
    matches!(1, 1) || true
}

```

using the following command line invocation:

```
<command>
```

with Kani version: 0.54.0

I expected to see this happen: *explanation*

Instead, this happened: *explanation*
```
Kani Rust Verifier 0.54.0 (standalone)
error[E0658]: attributes on expressions are experimental
 --> l.rs:2:5
  |
2 |     #[kani::proof]
  |     ^^^^^^^^^^^^^^
  |
  = note: see issue #15701 <https://github.com/rust-lang/rust/issues/15701> for more information
  = help: add `#![feature(stmt_expr_attributes)]` to the crate attributes to enable
  = note: this compiler was built on 2024-08-06; consider upgrading it if it is out of date

error[E0658]: custom attributes cannot be applied to expressions
 --> l.rs:2:5
  |
2 |     #[kani::proof]
  |     ^^^^^^^^^^^^^^
  |
  = note: see issue #54727 <https://github.com/rust-lang/rust/issues/54727> for more information
  = help: add `#![feature(proc_macro_hygiene)]` to the crate attributes to enable
  = note: this compiler was built on 2024-08-06; consider upgrading it if it is out of date

thread 'rustc' panicked at /rustc/60d146580c10036ce89e019422c6bc2fd9729b65/compiler/rustc_ast/src/tokenstream.rs:456:54:
missing tokens for node: Expr { id: NodeId(4294967040), kind: MacCall(MacCall { path: Path { span: l.rs:3:5: 3:12 (#0), segments: [PathSegment { ident: matches#0, id: NodeId(4294967040), args: None }], tokens: None }, args: DelimArgs { dspan: DelimSpan { open: l.rs:3:13: 3:14 (#0), close: l.rs:3:18: 3:19 (#0) }, delim: Parenthesis, tokens: TokenStream([Token(Token { kind: Literal(Lit { kind: Integer, symbol: "1", suffix: None }), span: l.rs:3:14: 3:15 (#0) }, Joint), Token(Token { kind: Comma, span: l.rs:3:15: 3:16 (#0) }, Alone), Token(Token { kind: Literal(Lit { kind: Integer, symbol: "1", suffix: None }), span: l.rs:3:17: 3:18 (#0) }, JointHidden)]) } }), span: l.rs:3:5: 3:19 (#0), attrs: [], tokens: None }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/60d146580c10036ce89e019422c6bc2fd9729b65/library/std/src/panicking.rs:662:5
   1: core::panicking::panic_fmt
             at /rustc/60d146580c10036ce89e019422c6bc2fd9729b65/library/core/src/panicking.rs:74:14
   2: <rustc_expand::base::Annotatable>::to_tokens
   3: <rustc_expand::expand::MacroExpander>::fully_expand_fragment
   4: <rustc_expand::expand::MacroExpander>::expand_crate
   5: rustc_interface::passes::resolver_for_lowering_raw
      [... omitted 2 frames ...]
   6: rustc_interface::interface::run_compiler::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Kani unexpectedly panicked during compilation.
Please file an issue here: https://github.com/model-checking/kani/issues/new?labels=bug&template=bug_report.md
error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0658`.
error: /home/matthias/.kani/kani-0.54.0/bin/kani-compiler exited with status exit status: 101
```

**Comment by matthiaskrgr** [comment]
tbh this looks more like a rustc crash that a kani crash.
Is there a way for kani to dump the resulting / expanded rustc code that it feeds into rustc, in order to check if this ICEs with standalone rustc? :thinking:

**Comment by zhassan-aws** [comment]
Normally, this can be done using `RUSTFLAGS="-Zunpretty=expanded" cargo kani`. For example, running it on a hello world program produces:
```bash
$ RUSTFLAGS="-Zunpretty=expanded" cargo kani
Kani Rust Verifier 0.54.0 (cargo plugin)
   Compiling t12 v0.1.0 (/home/ubuntu/examples/t12)
#![feature(prelude_import)]
#![feature(register_tool)]
#![register_tool(kanitool)]
#[prelude_import]
use std::prelude::rust_2021::*;
#[macro_use]
extern crate std;
fn main() { { let _ = format_args!("Hello, world!"); }; }
```
But in the test you posted, it doesn't seem to be working:
```bash
$ RUSTFLAGS="-Zunpretty=expanded" cargo kani
Kani Rust Verifier 0.54.0 (cargo plugin)
   Compiling iss3446 v0.1.0 (/home/ubuntu/examples/iss3446)
error[E0658]: attributes on expressions are experimental
 --> src/main.rs:2:5
  |
2 |     #[kani::proof]
  |     ^^^^^^^^^^^^^^
  |
  = note: see issue #15701 <https://github.com/rust-lang/rust/issues/15701> for more information
  = help: add `#![feature(stmt_expr_attributes)]` to the crate attributes to enable
  = note: this compiler was built on 2024-08-06; consider upgrading it if it is out of date

thread 'rustc' panicked at /rustc/60d146580c10036ce89e019422c6bc2fd9729b65/compiler/rustc_ast/src/tokenstream.rs:456:54:
missing tokens for node: Expr { id: NodeId(4294967040), kind: MacCall(MacCall { path: Path { span: src/main.rs:3:5: 3:12 (#0), segments: [PathSegment { ident: matches#0, id: NodeId(4294967040), args: None }], tokens: None }, args: DelimArgs { dspan: DelimSpan { open: src/main.rs:3:13: 3:14 (#0), close: src/main.rs:3:18: 3:19 (#0) }, delim: Parenthesis, tokens: TokenStream([Token(Token { kind: Literal(Lit { kind: Integer, symbol: "1", suffix: None }), span: src/main.rs:3:14: 3:15 (#0) }, Joint), Token(Token { kind: Comma, span: src/main.rs:3:15: 3:16 (#0) }, Alone), Token(Token { kind: Literal(Lit { kind: Integer, symbol: "1", suffix: None }), span: src/main.rs:3:17: 3:18 (#0) }, JointHidden)]) } }), span: src/main.rs:3:5: 3:19 (#0), attrs: [], tokens: None }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Kani unexpectedly panicked during compilation.error[E0658]: custom attributes cannot be applied to expressions
 --> src/main.rs:2:5
  |
2 |     #[kani::proof]
  |     ^^^^^^^^^^^^^^
  |
  = note: see issue #54727 <https://github.com/rust-lang/rust/issues/54727> for more information
  = help: add `#![feature(proc_macro_hygiene)]` to the crate attributes to enable
  = note: this compiler was built on 2024-08-06; consider upgrading it if it is out of date


Please file an issue here: https://github.com/model-checking/kani/issues/new?labels=bug&template=bug_report.md
error: internal compiler error: Kani unexpectedly panicked at panicked at /rustc/60d146580c10036ce89e019422c6bc2fd9729b65/compiler/rustc_ast/src/tokenstream.rs:456:54:
                                missing tokens for node: Expr { id: NodeId(4294967040), kind: MacCall(MacCall { path: Path { span: src/main.rs:3:5: 3:12 (#0), segments: [PathSegment { ident: matches#0, id: NodeId(4294967040), args: None }], tokens: None }, args: DelimArgs { dspan: DelimSpan { open: src/main.rs:3:13: 3:14 (#0), close: src/main.rs:3:18: 3:19 (#0) }, delim: Parenthesis, tokens: TokenStream([Token(Token { kind: Literal(Lit { kind: Integer, symbol: "1", suffix: None }), span: src/main.rs:3:14: 3:15 (#0) }, Joint), Token(Token { kind: Comma, span: src/main.rs:3:15: 3:16 (#0) }, Alone), Token(Token { kind: Literal(Lit { kind: Integer, symbol: "1", suffix: None }), span: src/main.rs:3:17: 3:18 (#0) }, JointHidden)]) } }), span: src/main.rs:3:5: 3:19 (#0), attrs: [], tokens: None }.

error: could not compile `iss3446` (bin "iss3446") due to 3 previous errors
error: Failed to compile `iss3446` due to an internal compiler error.: error: internal compiler error: Kani unexpectedly panicked at panicked at /rustc/60d146580c10036ce89e019422c6bc2fd9729b65/compiler/rustc_ast/src/tokenstream.rs:456:54:
                                missing tokens for node: Expr { id: NodeId(4294967040), kind: MacCall(MacCall { path: Path { span: src/main.rs:3:5: 3:12 (#0), segments: [PathSegment { ident: matches#0, id: NodeId(4294967040), args: None }], tokens: None }, args: DelimArgs { dspan: DelimSpan { open: src/main.rs:3:13: 3:14 (#0), close: src/main.rs:3:18: 3:19 (#0) }, delim: Parenthesis, tokens: TokenStream([Token(Token { kind: Literal(Lit { kind: Integer, symbol: "1", suffix: None }), span: src/main.rs:3:14: 3:15 (#0) }, Joint), Token(Token { kind: Comma, span: src/main.rs:3:15: 3:16 (#0) }, Alone), Token(Token { kind: Literal(Lit { kind: Integer, symbol: "1", suffix: None }), span: src/main.rs:3:17: 3:18 (#0) }, JointHidden)]) } }), span: src/main.rs:3:5: 3:19 (#0), attrs: [], tokens: None }.
```
