### ISSUE TITLE
Unexpected panic: fat pointer?

### ISSUE THREAD

**Issue by vecchiot-aws** [model-checking/kani#378]
File: `main.rs`
```Rust
trait T {
    fn call(&self) {
        
    }
}

struct A;

impl T for A {}

fn main() {
    let boxed_t: &[Box<dyn T>] = &[Box::new(A)];
    boxed_t[0].call();
}
```

Command: `rmc main.rs`

Expected: Successful verification

Result: 
```
thread 'rustc' panicked at 'assertion failed: before.fat_ptr_mir_typ.is_none()', compiler/rustc_codegen_llvm/src/gotoc/place.rs:263:21
stack backtrace:
   0: rust_begin_unwind
             at /Users/vecchiot/Documents/rmc/library/std/src/panicking.rs:516:5
   1: core::panicking::panic_fmt
             at /Users/vecchiot/Documents/rmc/library/core/src/panicking.rs:93:14
   2: core::panicking::panic
             at /Users/vecchiot/Documents/rmc/library/core/src/panicking.rs:50:5
   3: rustc_codegen_llvm::gotoc::place::<impl rustc_codegen_llvm::gotoc::metadata::GotocCtx>::codegen_projection
             at /Users/vecchiot/Documents/rmc/compiler/rustc_codegen_llvm/src/gotoc/place.rs:263:21
   4: rustc_codegen_llvm::gotoc::place::<impl rustc_codegen_llvm::gotoc::metadata::GotocCtx>::codegen_place::{{closure}}
             at /Users/vecchiot/Documents/rmc/compiler/rustc_codegen_llvm/src/gotoc/place.rs:403:53
   5: core::iter::adapters::copied::copy_fold::{{closure}}
             at /Users/vecchiot/Documents/rmc/library/core/src/iter/adapters/copied.rs:28:22
   6: core::iter::traits::iterator::Iterator::fold
             at /Users/vecchiot/Documents/rmc/library/core/src/iter/traits/iterator.rs:2174:21
   7: <core::iter::adapters::copied::Copied<I> as core::iter::traits::iterator::Iterator>::fold
             at /Users/vecchiot/Documents/rmc/library/core/src/iter/adapters/copied.rs:64:9
   8: rustc_codegen_llvm::gotoc::place::<impl rustc_codegen_llvm::gotoc::metadata::GotocCtx>::codegen_place
             at /Users/vecchiot/Documents/rmc/compiler/rustc_codegen_llvm/src/gotoc/place.rs:401:9
   9: rustc_codegen_llvm::gotoc::rvalue::<impl rustc_codegen_llvm::gotoc::metadata::GotocCtx>::codegen_rvalue_ref
             at /Users/vecchiot/Documents/rmc/compiler/rustc_codegen_llvm/src/gotoc/rvalue.rs:100:26
  10: rustc_codegen_llvm::gotoc::rvalue::<impl rustc_codegen_llvm::gotoc::metadata::GotocCtx>::codegen_rvalue
             at /Users/vecchiot/Documents/rmc/compiler/rustc_codegen_llvm/src/gotoc/rvalue.rs:381:63
  11: rustc_codegen_llvm::gotoc::statement::<impl rustc_codegen_llvm::gotoc::metadata::GotocCtx>::codegen_statement
             at /Users/vecchiot/Documents/rmc/compiler/rustc_codegen_llvm/src/gotoc/statement.rs:462:60
  12: rustc_codegen_llvm::gotoc::<impl rustc_codegen_llvm::gotoc::metadata::GotocCtx>::codegen_block
             at /Users/vecchiot/Documents/rmc/compiler/rustc_codegen_llvm/src/gotoc/mod.rs:120:29
  13: rustc_codegen_llvm::gotoc::<impl rustc_codegen_llvm::gotoc::metadata::GotocCtx>::codegen_function::{{closure}}
             at /Users/vecchiot/Documents/rmc/compiler/rustc_codegen_llvm/src/gotoc/mod.rs:207:71
  14: core::iter::traits::iterator::Iterator::for_each::call::{{closure}}
             at /Users/vecchiot/Documents/rmc/library/core/src/iter/traits/iterator.rs:734:29
  15: core::iter::adapters::map::map_fold::{{closure}}
             at /Users/vecchiot/Documents/rmc/library/core/src/iter/adapters/map.rs:84:21
  16: <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::fold::enumerate::{{closure}}
             at /Users/vecchiot/Documents/rmc/library/core/src/iter/adapters/enumerate.rs:106:27
  17: core::iter::traits::iterator::Iterator::fold
             at /Users/vecchiot/Documents/rmc/library/core/src/iter/traits/iterator.rs:2174:21
  18: <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::fold
             at /Users/vecchiot/Documents/rmc/library/core/src/iter/adapters/enumerate.rs:112:9
  19: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /Users/vecchiot/Documents/rmc/library/core/src/iter/adapters/map.rs:124:9
  20: core::iter::traits::iterator::Iterator::for_each
             at /Users/vecchiot/Documents/rmc/library/core/src/iter/traits/iterator.rs:737:9
  21: rustc_codegen_llvm::gotoc::<impl rustc_codegen_llvm::gotoc::metadata::GotocCtx>::codegen_function
             at /Users/vecchiot/Documents/rmc/compiler/rustc_codegen_llvm/src/gotoc/mod.rs:207:13
  22: <rustc_codegen_llvm::gotoc::GotocCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate::{{closure}}
             at /Users/vecchiot/Documents/rmc/compiler/rustc_codegen_llvm/src/gotoc/mod.rs:391:35
  23: rustc_codegen_llvm::gotoc::<impl rustc_codegen_llvm::gotoc::metadata::GotocCtx>::call_with_panic_debug_info::{{closure}}
             at /Users/vecchiot/Documents/rmc/compiler/rustc_codegen_llvm/src/gotoc/mod.rs:103:13
  24: std::thread::local::LocalKey<T>::try_with
             at /Users/vecchiot/Documents/rmc/library/std/src/thread/local.rs:399:16
  25: std::thread::local::LocalKey<T>::with
             at /Users/vecchiot/Documents/rmc/library/std/src/thread/local.rs:375:9
  26: rustc_codegen_llvm::gotoc::<impl rustc_codegen_llvm::gotoc::metadata::GotocCtx>::call_with_panic_debug_info
             at /Users/vecchiot/Documents/rmc/compiler/rustc_codegen_llvm/src/gotoc/mod.rs:101:9
  27: <rustc_codegen_llvm::gotoc::GotocCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
             at /Users/vecchiot/Documents/rmc/compiler/rustc_codegen_llvm/src/gotoc/mod.rs:390:25
  28: rustc_interface::passes::start_codegen::{{closure}}
             at /Users/vecchiot/Documents/rmc/compiler/rustc_interface/src/passes.rs:1056:9
  29: rustc_data_structures::profiling::VerboseTimingGuard::run
             at /Users/vecchiot/Documents/rmc/compiler/rustc_data_structures/src/profiling.rs:611:9
  30: rustc_session::utils::<impl rustc_session::session::Session>::time
             at /Users/vecchiot/Documents/rmc/compiler/rustc_session/src/utils.rs:16:9
  31: rustc_interface::passes::start_codegen
             at /Users/vecchiot/Documents/rmc/compiler/rustc_interface/src/passes.rs:1055:19
  32: rustc_interface::queries::Queries::ongoing_codegen::{{closure}}::{{closure}}
             at /Users/vecchiot/Documents/rmc/compiler/rustc_interface/src/queries.rs:254:20
  33: rustc_interface::passes::QueryContext::enter::{{closure}}
             at /Users/vecchiot/Documents/rmc/compiler/rustc_interface/src/passes.rs:780:42
  34: rustc_middle::ty::context::tls::enter_context::{{closure}}
             at /Users/vecchiot/Documents/rmc/compiler/rustc_middle/src/ty/context.rs:1784:50
  35: rustc_middle::ty::context::tls::set_tlv
             at /Users/vecchiot/Documents/rmc/compiler/rustc_middle/src/ty/context.rs:1768:9
  36: rustc_middle::ty::context::tls::enter_context
             at /Users/vecchiot/Documents/rmc/compiler/rustc_middle/src/ty/context.rs:1784:9
  37: rustc_interface::passes::QueryContext::enter
             at /Users/vecchiot/Documents/rmc/compiler/rustc_interface/src/passes.rs:780:9
  38: rustc_interface::queries::Queries::ongoing_codegen::{{closure}}
             at /Users/vecchiot/Documents/rmc/compiler/rustc_interface/src/queries.rs:245:13
  39: rustc_interface::queries::Query<T>::compute
             at /Users/vecchiot/Documents/rmc/compiler/rustc_interface/src/queries.rs:38:28
  40: rustc_interface::queries::Queries::ongoing_codegen
             at /Users/vecchiot/Documents/rmc/compiler/rustc_interface/src/queries.rs:243:9
  41: rustc_driver::run_compiler::{{closure}}::{{closure}}
             at /Users/vecchiot/Documents/rmc/compiler/rustc_driver/src/lib.rs:407:13
  42: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
             at /Users/vecchiot/Documents/rmc/compiler/rustc_interface/src/queries.rs:394:19
  43: rustc_driver::run_compiler::{{closure}}
             at /Users/vecchiot/Documents/rmc/compiler/rustc_driver/src/lib.rs:312:22
  44: rustc_interface::interface::create_compiler_and_run::{{closure}}
             at /Users/vecchiot/Documents/rmc/compiler/rustc_interface/src/interface.rs:209:13
  45: rustc_span::with_source_map
             at /Users/vecchiot/Documents/rmc/compiler/rustc_span/src/lib.rs:911:5
  46: rustc_interface::interface::create_compiler_and_run
             at /Users/vecchiot/Documents/rmc/compiler/rustc_interface/src/interface.rs:203:5
  47: rustc_interface::interface::run_compiler::{{closure}}
             at /Users/vecchiot/Documents/rmc/compiler/rustc_interface/src/interface.rs:225:12
  48: rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals::{{closure}}::{{closure}}
             at /Users/vecchiot/Documents/rmc/compiler/rustc_interface/src/util.rs:157:13
  49: scoped_tls::ScopedKey<T>::set
             at /Users/vecchiot/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137:9
  50: rustc_span::create_session_globals_then
             at /Users/vecchiot/Documents/rmc/compiler/rustc_span/src/lib.rs:105:5
  51: rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals::{{closure}}
             at /Users/vecchiot/Documents/rmc/compiler/rustc_interface/src/util.rs:155:9
  52: rustc_interface::util::scoped_thread::{{closure}}
             at /Users/vecchiot/Documents/rmc/compiler/rustc_interface/src/util.rs:130:24
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.56.0-dev running on x86_64-apple-darwin

note: compiler flags: -Z codegen-backend=gotoc -Z symbol-mangling-version=v0 -Z symbol_table_passes=

query stack during panic:
end of query stack

[RMC] current codegen item: codegen_function: main

RMC unexpectedly panicked during code generation.

If you are seeing this message, please file an issue here instead of on the Rust compiler: https://github.com/model-checking/rmc/issues/new?labels=bug&template=bug_report.md
```

**Comment by zhassan-aws** [comment]
May require tracking a stack of fat pointers as opposed to a single one in the projection code.
