### ISSUE TITLE
Assertion failure in codegen of crossbeam-epoch crate

### ISSUE THREAD

**Issue by zhassan-aws** [model-checking/kani#504]
RMC runs into an assertion failure `self.typ.is_pointer() ` in codegen of `crossbeam-epoch` crate.

Steps to reproduce:

1. `cargo new iss504`
2. Add `crossbeam-epoch` as a dependency in `Cargo.toml`:
```
[dependencies]
crossbeam-epoch = "0.9"
```
3. Run
```
RUST_BACKTRACE=1 RUSTFLAGS="-Z trim-diagnostic-paths=no -Z codegen-backend=gotoc --cfg=rmc" RUSTC=rmc-rustc cargo build --target x86_64-unknown-linux-gnu -j1
```

This produces the following:
```
$ RUST_BACKTRACE=1 RUSTFLAGS="-Z trim-diagnostic-paths=no -Z codegen-backend=gotoc --cfg=rmc" RUSTC=rmc-rustc cargo build --target x86_64-unknown-linux-gnu -j1
    Updating crates.io index
   Compiling autocfg v1.0.1
   Compiling crossbeam-utils v0.8.5
   Compiling cfg-if v1.0.0
   Compiling lazy_static v1.4.0
   Compiling crossbeam-epoch v0.9.5
   Compiling scopeguard v1.1.0
   Compiling memoffset v0.6.4
thread 'rustc' panicked at 'assertion failed: self.typ.is_pointer()', compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/expr.rs:472:9
stack backtrace:
   0: rust_begin_unwind
             at /home/ubuntu/tools/rmc/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /home/ubuntu/tools/rmc/library/core/src/panicking.rs:96:14
   2: core::panicking::panic
             at /home/ubuntu/tools/rmc/library/core/src/panicking.rs:50:5
   3: rustc_codegen_llvm::gotoc::cbmc::goto_program::expr::Expr::dereference
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_llvm/src/gotoc/cbmc/goto_program/expr.rs:472:9
   4: rustc_codegen_llvm::gotoc::mir_to_goto::codegen::place::<impl rustc_codegen_llvm::gotoc::mir_to_goto::context::goto_ctx::GotocCtx>::codegen_projection
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_llvm/src/gotoc/mir_to_goto/codegen/place.rs:343:26
   5: rustc_codegen_llvm::gotoc::mir_to_goto::codegen::place::<impl rustc_codegen_llvm::gotoc::mir_to_goto::context::goto_ctx::GotocCtx>::codegen_place::{{closure}}
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_llvm/src/gotoc/mir_to_goto/codegen/place.rs:469:53
   6: core::iter::adapters::copied::copy_fold::{{closure}}
             at /home/ubuntu/tools/rmc/library/core/src/iter/adapters/copied.rs:28:22
   7: core::iter::traits::iterator::Iterator::fold
             at /home/ubuntu/tools/rmc/library/core/src/iter/traits/iterator.rs:2164:21
   8: <core::iter::adapters::copied::Copied<I> as core::iter::traits::iterator::Iterator>::fold
             at /home/ubuntu/tools/rmc/library/core/src/iter/adapters/copied.rs:64:9
   9: rustc_codegen_llvm::gotoc::mir_to_goto::codegen::place::<impl rustc_codegen_llvm::gotoc::mir_to_goto::context::goto_ctx::GotocCtx>::codegen_place
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_llvm/src/gotoc/mir_to_goto/codegen/place.rs:467:9
  10: rustc_codegen_llvm::gotoc::mir_to_goto::codegen::operand::<impl rustc_codegen_llvm::gotoc::mir_to_goto::context::goto_ctx::GotocCtx>::codegen_operand
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_llvm/src/gotoc/mir_to_goto/codegen/operand.rs:31:34
  11: rustc_codegen_llvm::gotoc::mir_to_goto::codegen::statement::<impl rustc_codegen_llvm::gotoc::mir_to_goto::context::goto_ctx::GotocCtx>::codegen_funcall::{{closure}}
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_llvm/src/gotoc/mir_to_goto/codegen/statement.rs:313:26
  12: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /home/ubuntu/tools/rmc/library/core/src/ops/function.rs:269:13
  13: <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::find_map
             at /home/ubuntu/tools/rmc/library/core/src/slice/iter/macros.rs:276:38
  14: <core::iter::adapters::filter_map::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::next
             at /home/ubuntu/tools/rmc/library/core/src/iter/adapters/filter_map.rs:61:9
  15: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /home/ubuntu/tools/rmc/library/alloc/src/vec/spec_from_iter_nested.rs:23:32
  16: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /home/ubuntu/tools/rmc/library/alloc/src/vec/spec_from_iter.rs:33:9
  17: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /home/ubuntu/tools/rmc/library/alloc/src/vec/mod.rs:2485:9
  18: core::iter::traits::iterator::Iterator::collect
             at /home/ubuntu/tools/rmc/library/core/src/iter/traits/iterator.rs:1739:9
  19: rustc_codegen_llvm::gotoc::mir_to_goto::codegen::statement::<impl rustc_codegen_llvm::gotoc::mir_to_goto::context::goto_ctx::GotocCtx>::codegen_funcall
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_llvm/src/gotoc/mir_to_goto/codegen/statement.rs:304:33
  20: rustc_codegen_llvm::gotoc::mir_to_goto::codegen::statement::<impl rustc_codegen_llvm::gotoc::mir_to_goto::context::goto_ctx::GotocCtx>::codegen_terminator
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_llvm/src/gotoc/mir_to_goto/codegen/statement.rs:64:17
  21: rustc_codegen_llvm::gotoc::mir_to_goto::codegen::block::<impl rustc_codegen_llvm::gotoc::mir_to_goto::context::goto_ctx::GotocCtx>::codegen_block
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_llvm/src/gotoc/mir_to_goto/codegen/block.rs:18:29
  22: rustc_codegen_llvm::gotoc::mir_to_goto::codegen::function::<impl rustc_codegen_llvm::gotoc::mir_to_goto::context::goto_ctx::GotocCtx>::codegen_function::{{closure}}
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_llvm/src/gotoc/mir_to_goto/codegen/function.rs:99:71
  23: core::iter::traits::iterator::Iterator::for_each::call::{{closure}}
             at /home/ubuntu/tools/rmc/library/core/src/iter/traits/iterator.rs:724:29
  24: core::iter::adapters::map::map_fold::{{closure}}
             at /home/ubuntu/tools/rmc/library/core/src/iter/adapters/map.rs:84:21
  25: <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::fold::enumerate::{{closure}}
             at /home/ubuntu/tools/rmc/library/core/src/iter/adapters/enumerate.rs:106:27
  26: core::iter::traits::iterator::Iterator::fold
             at /home/ubuntu/tools/rmc/library/core/src/iter/traits/iterator.rs:2164:21
  27: <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::fold
             at /home/ubuntu/tools/rmc/library/core/src/iter/adapters/enumerate.rs:112:9
  28: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /home/ubuntu/tools/rmc/library/core/src/iter/adapters/map.rs:124:9
  29: core::iter::traits::iterator::Iterator::for_each
             at /home/ubuntu/tools/rmc/library/core/src/iter/traits/iterator.rs:727:9
  30: rustc_codegen_llvm::gotoc::mir_to_goto::codegen::function::<impl rustc_codegen_llvm::gotoc::mir_to_goto::context::goto_ctx::GotocCtx>::codegen_function
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_llvm/src/gotoc/mir_to_goto/codegen/function.rs:99:13
  31: <rustc_codegen_llvm::gotoc::mir_to_goto::compiler_interface::GotocCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate::{{closure}}
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_llvm/src/gotoc/mir_to_goto/compiler_interface.rs:97:35
  32: rustc_codegen_llvm::gotoc::mir_to_goto::utils::debug::<impl rustc_codegen_llvm::gotoc::mir_to_goto::context::goto_ctx::GotocCtx>::call_with_panic_debug_info::{{closure}}
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_llvm/src/gotoc/mir_to_goto/utils/debug.rs:77:13
  33: std::thread::local::LocalKey<T>::try_with
             at /home/ubuntu/tools/rmc/library/std/src/thread/local.rs:399:16
  34: std::thread::local::LocalKey<T>::with
             at /home/ubuntu/tools/rmc/library/std/src/thread/local.rs:375:9
  35: rustc_codegen_llvm::gotoc::mir_to_goto::utils::debug::<impl rustc_codegen_llvm::gotoc::mir_to_goto::context::goto_ctx::GotocCtx>::call_with_panic_debug_info
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_llvm/src/gotoc/mir_to_goto/utils/debug.rs:75:9
  36: <rustc_codegen_llvm::gotoc::mir_to_goto::compiler_interface::GotocCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_llvm/src/gotoc/mir_to_goto/compiler_interface.rs:96:25
  37: rustc_interface::passes::start_codegen::{{closure}}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/passes.rs:1052:9
  38: rustc_data_structures::profiling::VerboseTimingGuard::run
             at /home/ubuntu/tools/rmc/compiler/rustc_data_structures/src/profiling.rs:611:9
  39: rustc_session::utils::<impl rustc_session::session::Session>::time
             at /home/ubuntu/tools/rmc/compiler/rustc_session/src/utils.rs:16:9
  40: rustc_interface::passes::start_codegen
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/passes.rs:1051:19
  41: rustc_interface::queries::Queries::ongoing_codegen::{{closure}}::{{closure}}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/queries.rs:254:20
  42: rustc_interface::passes::QueryContext::enter::{{closure}}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/passes.rs:778:42
  43: rustc_middle::ty::context::tls::enter_context::{{closure}}
             at /home/ubuntu/tools/rmc/compiler/rustc_middle/src/ty/context.rs:1785:50
  44: rustc_middle::ty::context::tls::set_tlv
             at /home/ubuntu/tools/rmc/compiler/rustc_middle/src/ty/context.rs:1769:9
  45: rustc_middle::ty::context::tls::enter_context
             at /home/ubuntu/tools/rmc/compiler/rustc_middle/src/ty/context.rs:1785:9
  46: rustc_interface::passes::QueryContext::enter
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/passes.rs:778:9
  47: rustc_interface::queries::Queries::ongoing_codegen::{{closure}}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/queries.rs:245:13
  48: rustc_interface::queries::Query<T>::compute
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/queries.rs:38:28
  49: rustc_interface::queries::Queries::ongoing_codegen
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/queries.rs:243:9
  50: rustc_driver::run_compiler::{{closure}}::{{closure}}
             at /home/ubuntu/tools/rmc/compiler/rustc_driver/src/lib.rs:407:13
  51: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/queries.rs:394:19
  52: rustc_driver::run_compiler::{{closure}}
             at /home/ubuntu/tools/rmc/compiler/rustc_driver/src/lib.rs:312:22
  53: rustc_interface::interface::create_compiler_and_run::{{closure}}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/interface.rs:209:13
  54: rustc_span::with_source_map
             at /home/ubuntu/tools/rmc/compiler/rustc_span/src/lib.rs:956:5
  55: rustc_interface::interface::create_compiler_and_run
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/interface.rs:203:5
  56: rustc_interface::interface::run_compiler::{{closure}}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/interface.rs:225:12
  57: rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals::{{closure}}::{{closure}}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/util.rs:157:13
  58: scoped_tls::ScopedKey<T>::set
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137:9
  59: rustc_span::create_session_globals_then
             at /home/ubuntu/tools/rmc/compiler/rustc_span/src/lib.rs:106:5
  60: rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals::{{closure}}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/util.rs:155:9
  61: rustc_interface::util::scoped_thread::{{closure}}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/util.rs:130:24
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.57.0-dev running on x86_64-unknown-linux-gnu

note: compiler flags: -Z trim-diagnostic-paths=no -Z codegen-backend=gotoc -C embed-bitcode=no -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack

[RMC] current codegen item: codegen_function: std::ptr::drop_in_place
_ZN4core3ptr83drop_in_place$LT$alloc..boxed..Box$LT$crossbeam_epoch..internal..no_op_func$GT$$GT$17hacb4960c6aa3ff74E

RMC unexpectedly panicked during code generation.

If you are seeing this message, please file an issue here instead of on the Rust compiler: https://github.com/model-checking/rmc/issues/new?labels=bug&template=bug_report.md
error: could not compile `crossbeam-epoch`

To learn more, run the command again with --verbose.
```

**Comment by avanhatt** [comment]
The issue seemed to be an attempt to dereference this type:
```
Adt(
    std::boxed::Box,
    [
        fn() {internal::no_op_func},
        std::alloc::Global,
    ],
)
``` 

We handle the case of boxed unsized types, but are grokking this as sized. Attempting a fix now.

**Comment by danielsn** [comment]
On my mac, (and removing the gnu target) I get

```
FlexibleArray { typ: StructTag("tag-str") }
   Compiling cfg-if v1.0.0
   Compiling lazy_static v1.4.0
   Compiling scopeguard v1.1.0
   Compiling memoffset v0.6.5
error: extern location for autocfg does not exist: /Users/dsn/temp/iss504/target/debug/deps/libautocfg-88edecb1d65358ee.rlib
 --> /Users/dsn/.cargo/registry/src/github.com-1ecc6299db9ec823/memoffset-0.6.5/build.rs:1:1
  |
1 | extern crate autocfg;
  | ^^^^^^^^^^^^^^^^^^^^^

```

**Comment by zhassan-aws** [comment]
Try with the new RMC invoke command:
```
RUST_BACKTRACE=1 RUSTFLAGS=$(rmc-rustc --rmc-flags) RUSTC=$(rmc-rustc --rmc-path) cargo build --target x86_64-unknown-linux-gnu -j1
```
(removing the `--target` option if on mac)

**Comment by celinval** [comment]
I followed the steps above to create the testcase and I ran `cargo kani --debug`. Cargo is failing after trying to compile `crossbeam_utils`, but looking at the compiler logs, it looks like the crate was built.:

```
DEBUG kani_compiler::codegen_cprover_gotoc::compiler_interface output to "/tmp/bar/target/x86_64-unknown-linux-gnu/debug/deps/crossbeam_utils-556f152027efad54.symtab.json"
DEBUG kani_compiler::codegen_cprover_gotoc::compiler_interface output to "/tmp/bar/target/x86_64-unknown-linux-gnu/debug/deps/crossbeam_utils-556f152027efad54.type_map.json"
DEBUG kani_compiler::codegen_cprover_gotoc::compiler_interface output to "/tmp/bar/target/x86_64-unknown-linux-gnu/debug/deps/crossbeam_utils-556f152027efad54.kani-metadata.json"
error: build failed
Error: cargo exited with status exit status: 101
```

**Comment by zhassan-aws** [comment]
Was the `crossbeam-epoch` crate also built? The previous issue I've seen was with that crate:
```
error: could not compile `crossbeam-epoch`
```

**Comment by celinval** [comment]
Ah, that makes sense. There are so many warnings now that I didn't see the actual error which is with `crossbean-epoch`:
```
thread 'rustc' panicked at 'removal index (is 0) should be < len (is 0)', src/kani-compiler/src/codegen_cprover_gotoc/overrides/hooks.rs:498:25
```

**Comment by tedinski** [comment]
This no longer seems to fail with this test setup:

```
$ cargo new crossbeam-epoch-test
     Created binary (application) `crossbeam-epoch-test` package
$ cd crossbeam-epoch-test/
$ cargo add crossbeam-epoch
    Updating crates.io index
      Adding crossbeam-epoch v0.9.10 to dependencies.
             Features:
             + alloc
             + once_cell
             + std
             - loom
             - loom-crate
             - nightly
$ cargo kani
   Compiling autocfg v1.1.0
   Compiling crossbeam-utils v0.8.11
   Compiling once_cell v1.13.1
   Compiling cfg-if v1.0.0
   Compiling scopeguard v1.1.0
   Compiling memoffset v0.6.5
   Compiling crossbeam-epoch v0.9.10
   Compiling crossbeam-epoch-test v0.1.0 (/home/ubuntu/experiments/specific_crate_failures/crossbeam-epoch-test)
    Finished dev [unoptimized + debuginfo] target(s) in 5.87s
Error: No proof harnesses (functions with #[kani::proof]) were found to verify.
```

Close this issue?

**Comment by zhassan-aws** [comment]
Confirmed. Closing it.
