### ISSUE TITLE
Panic due to unwrapping ` None` during codegen of tokio crate

### ISSUE THREAD

**Issue by zhassan-aws** [model-checking/kani#674]
Steps to reproduce:
1. `cargo new foo`
2. `cd foo`
3. Add `tokio` to the dependencies in `Cargo.toml`:
 ```
[dependencies]
tokio = { version = "1.14.0", features = ["full"] }
```
4. Run:
```
RUST_BACKTRACE=1 RUSTFLAGS=$(rmc-rustc --rmc-flags) RUSTC=$(rmc-rustc --rmc-path) cargo build --target x86_64-unknown-linux-gnu -j1
```

with RMC version: `7d0d4cfc6da`

I expected to see this happen: Verification successful

Instead, this happened:
```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_codegen_rmc/src/codegen/typ.rs:1194:91
stack backtrace:
   0: rust_begin_unwind
             at /home/ubuntu/tools/rmc/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /home/ubuntu/tools/rmc/library/core/src/panicking.rs:107:14
   2: core::panicking::panic
             at /home/ubuntu/tools/rmc/library/core/src/panicking.rs:48:5
   3: <rustc_codegen_rmc::context::goto_ctx::GotocCtx>::fn_typ
   4: <rustc_codegen_rmc::context::goto_ctx::GotocCtx>::declare_function::{closure#0}
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_rmc/src/codegen/function.rs:194:17
   5: <rustc_codegen_rmc::context::goto_ctx::GotocCtx>::ensure::<<rustc_codegen_rmc::context::goto_ctx::GotocCtx>::declare_function::{closure#0}, &alloc::string::String>
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_rmc/src/context/goto_ctx.rs:135:23
   6: <rustc_codegen_rmc::context::goto_ctx::GotocCtx>::declare_function
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_rmc/src/codegen/function.rs:190:9
   7: <rustc_codegen_rmc::compiler_interface::GotocCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate::{closure#0}
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_rmc/src/compiler_interface.rs:80:35
   8: <rustc_codegen_rmc::context::goto_ctx::GotocCtx>::call_with_panic_debug_info::<<rustc_codegen_rmc::compiler_interface::GotocCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate::{closure#0}>::{closure#0}
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_rmc/src/utils/debug.rs:87:13
   9: <std::thread::local::LocalKey<core::cell::RefCell<(core::option::Option<alloc::string::String>, core::option::Option<cbmc::goto_program::location::Location>)>>>::try_with::<<rustc_codegen_rmc::context::goto_ctx::GotocCtx>::call_with_panic_debug_info<<rustc_codegen_rmc::compiler_interface::GotocCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate::{closure#0}>::{closure#0}, ()>
             at /home/ubuntu/tools/rmc/library/std/src/thread/local.rs:399:16
  10: <std::thread::local::LocalKey<core::cell::RefCell<(core::option::Option<alloc::string::String>, core::option::Option<cbmc::goto_program::location::Location>)>>>::with::<<rustc_codegen_rmc::context::goto_ctx::GotocCtx>::call_with_panic_debug_info<<rustc_codegen_rmc::compiler_interface::GotocCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate::{closure#0}>::{closure#0}, ()>
             at /home/ubuntu/tools/rmc/library/std/src/thread/local.rs:375:9
  11: <rustc_codegen_rmc::context::goto_ctx::GotocCtx>::call_with_panic_debug_info::<<rustc_codegen_rmc::compiler_interface::GotocCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate::{closure#0}>
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_rmc/src/utils/debug.rs:84:9
  12: <rustc_codegen_rmc::compiler_interface::GotocCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
             at /home/ubuntu/tools/rmc/compiler/rustc_codegen_rmc/src/compiler_interface.rs:79:25
  13: rustc_interface::passes::start_codegen::{closure#0}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/passes.rs:1077:9
  14: <rustc_data_structures::profiling::VerboseTimingGuard>::run::<alloc::boxed::Box<dyn core::any::Any>, rustc_interface::passes::start_codegen::{closure#0}>
             at /home/ubuntu/tools/rmc/compiler/rustc_data_structures/src/profiling.rs:644:9
  15: <rustc_session::session::Session>::time::<alloc::boxed::Box<dyn core::any::Any>, rustc_interface::passes::start_codegen::{closure#0}>
             at /home/ubuntu/tools/rmc/compiler/rustc_session/src/utils.rs:16:9
  16: rustc_interface::passes::start_codegen
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/passes.rs:1076:19
  17: <rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/queries.rs:254:20
  18: <rustc_interface::passes::QueryContext>::enter::<<rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_errors::ErrorReported>>::{closure#0}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/passes.rs:805:42
  19: rustc_middle::ty::context::tls::enter_context::<<rustc_interface::passes::QueryContext>::enter<<rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_errors::ErrorReported>>::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_errors::ErrorReported>>::{closure#0}
             at /home/ubuntu/tools/rmc/compiler/rustc_middle/src/ty/context.rs:1778:50
  20: rustc_middle::ty::context::tls::set_tlv::<rustc_middle::ty::context::tls::enter_context<<rustc_interface::passes::QueryContext>::enter<<rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_errors::ErrorReported>>::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_errors::ErrorReported>>::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_errors::ErrorReported>>
             at /home/ubuntu/tools/rmc/compiler/rustc_middle/src/ty/context.rs:1762:9
  21: rustc_middle::ty::context::tls::enter_context::<<rustc_interface::passes::QueryContext>::enter<<rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_errors::ErrorReported>>::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_errors::ErrorReported>>
             at /home/ubuntu/tools/rmc/compiler/rustc_middle/src/ty/context.rs:1778:9
  22: <rustc_interface::passes::QueryContext>::enter::<<rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_errors::ErrorReported>>
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/passes.rs:805:9
  23: <rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/queries.rs:245:13
  24: <rustc_interface::queries::Query<alloc::boxed::Box<dyn core::any::Any>>>::compute::<<rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}>
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/queries.rs:38:28
  25: rustc_driver::run_compiler::{closure#1}::{closure#2}
             at /home/ubuntu/tools/rmc/compiler/rustc_driver/src/lib.rs:409:13
  26: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorReported>>
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/queries.rs:394:19
  27: rustc_driver::run_compiler::{closure#1}
             at /home/ubuntu/tools/rmc/compiler/rustc_driver/src/lib.rs:314:22
  28: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#1}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/interface.rs:220:13
  29: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorReported>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
             at /home/ubuntu/tools/rmc/compiler/rustc_span/src/lib.rs:971:5
  30: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/interface.rs:214:5
  31: rustc_interface::interface::run_compiler::<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#0}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/interface.rs:236:12
  32: rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>::{closure#0}::{closure#0}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/util.rs:145:13
  33: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137:9
  34: rustc_span::create_session_globals_then::<core::result::Result<(), rustc_errors::ErrorReported>, rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>::{closure#0}::{closure#0}>
             at /home/ubuntu/tools/rmc/compiler/rustc_span/src/lib.rs:109:5
  35: rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>::{closure#0}
             at /home/ubuntu/tools/rmc/compiler/rustc_interface/src/util.rs:143:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.59.0-dev running on x86_64-unknown-linux-gnu

note: compiler flags: -Z codegen-backend=gotoc -Z trim-diagnostic-paths=no -Z human_readable_cgu_names -C embed-bitcode=no -C debuginfo=2 -C overflow-checks=on --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack

[RMC] current codegen item: declare_function: sync::watch::Receiver::<T>::changed::{closure#0}
[RMC] current codegen location: Loc { file: "/home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/sync/watch.rs", function: None, line: 360, col: Some(69) }

RMC unexpectedly panicked during code generation.

If you are seeing this message, please file an issue here instead of on the Rust compiler: https://github.com/model-checking/rmc/issues/new?labels=bug&template=bug_report.md
error: could not compile `tokio`
```

**Comment by zhassan-aws** [comment]
With `af11d38d93a`, the panic is not reproducible. However, `cargo kani --only-codegen` produces the following errors:
```
error[E0382]: borrow of moved value: `subsys.base`
   --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/num_cpus-1.13.1/src/linux.rs:177:45
    |
174 |             subsys.base, mntinfo.root, mntinfo.mount_point
    |             ----------- value moved here
...
177 |         let rel_from_root = some!(Path::new(&subsys.base).strip_prefix(&mntinfo.root).ok());
    |                                             ^^^^^^^^^^^^ value borrowed here after move
    |
    = note: move occurs because `subsys.base` has type `std::string::String`, which does not implement the `Copy` trait

error[E0382]: borrow of moved value: `mntinfo.root`
   --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/num_cpus-1.13.1/src/linux.rs:177:72
    |
174 |             subsys.base, mntinfo.root, mntinfo.mount_point
    |                          ------------ value moved here
...
177 |         let rel_from_root = some!(Path::new(&subsys.base).strip_prefix(&mntinfo.root).ok());
    |                                                                        ^^^^^^^^^^^^^ value borrowed here after move
    |
    = note: move occurs because `mntinfo.root` has type `std::string::String`, which does not implement the `Copy` trait

error[E0382]: use of moved value: `mntinfo.mount_point`
   --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/num_cpus-1.13.1/src/linux.rs:182:38
    |
174 |             subsys.base, mntinfo.root, mntinfo.mount_point
    |                                        ------------------- value moved here
...
182 |         let mut path = PathBuf::from(mntinfo.mount_point);
    |                                      ^^^^^^^^^^^^^^^^^^^ value used here after move
    |
    = note: move occurs because `mntinfo.mount_point` has type `std::string::String`, which does not implement the `Copy` trait

For more information about this error, try `rustc --explain E0382`.
error: could not compile `num_cpus` due to 3 previous errors
```
The errors are not reproducible with `cargo build` or `cargo +nightly-2022-03-09-x86_64-unknown-linux-gnu build`.

**Comment by zhassan-aws** [comment]
With the fix in #1061, this now panics with:
```
thread 'rustc' panicked at 'not yet implemented: [static generator@/home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/sync/watch.rs:453:69: 467:6] Generator(DefId(0:12852 ~ tokio[9b1b]::sync::watch::{impl#0}::changed::{closure#0}), [(), std::future::ResumeTy, (), std::result::Result<(), sync::watch::error::RecvError>, for<'r, 's> {std::future::ResumeTy, &'r mut sync::watch::Receiver<()>, sync::notify::Notified<'s>, ()}, (&mut sync::watch::Receiver<()>,)], Static)', src/kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs:833:39
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5f37001055c29982f4c27ee9edd90449c8e07774/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/5f37001055c29982f4c27ee9edd90449c8e07774/library/core/src/panicking.rs:143:14
   2: kani_compiler::codegen_cprover_gotoc::codegen::typ::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::codegen_ty_ref
             at /home/ubuntu/git/kani/src/kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs:833:39
   3: kani_compiler::codegen_cprover_gotoc::codegen::typ::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::codegen_ty_inner
             at /home/ubuntu/git/kani/src/kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs:547:76
   4: kani_compiler::codegen_cprover_gotoc::codegen::typ::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::codegen_ty
             at /home/ubuntu/git/kani/src/kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs:484:24
   5: kani_compiler::codegen_cprover_gotoc::codegen::typ::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::codegen_struct_fields
             at /home/ubuntu/git/kani/src/kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs:671:74
   6: kani_compiler::codegen_cprover_gotoc::codegen::typ::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::codegen_variant_struct_fields
             at /home/ubuntu/git/kani/src/kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs:921:9
   7: kani_compiler::codegen_cprover_gotoc::codegen::typ::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::codegen_struct::{{closure}}
             at /home/ubuntu/git/kani/src/kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs:907:13
   8: kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx::ensure_struct
             at /home/ubuntu/git/kani/src/kani-compiler/src/codegen_cprover_gotoc/context/goto_ctx.rs:222:30
   9: kani_compiler::codegen_cprover_gotoc::codegen::typ::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::codegen_struct
             at /home/ubuntu/git/kani/src/kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs:904:9
  10: kani_compiler::codegen_cprover_gotoc::codegen::typ::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::codegen_ty_inner
             at /home/ubuntu/git/kani/src/kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs:507:21
  11: kani_compiler::codegen_cprover_gotoc::codegen::typ::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::codegen_ty
             at /home/ubuntu/git/kani/src/kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs:484:24
  12: kani_compiler::codegen_cprover_gotoc::codegen::typ::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::fn_typ
             at /home/ubuntu/git/kani/src/kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs:1240:32
  13: kani_compiler::codegen_cprover_gotoc::codegen::function::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::declare_function::{{closure}}
             at /home/ubuntu/git/kani/src/kani-compiler/src/codegen_cprover_gotoc/codegen/function.rs:232:17
  14: kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx::ensure
             at /home/ubuntu/git/kani/src/kani-compiler/src/codegen_cprover_gotoc/context/goto_ctx.rs:165:23
  15: kani_compiler::codegen_cprover_gotoc::codegen::function::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::declare_function
             at /home/ubuntu/git/kani/src/kani-compiler/src/codegen_cprover_gotoc/codegen/function.rs:228:9
  16: <kani_compiler::codegen_cprover_gotoc::compiler_interface::GotocCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate::{{closure}}
             at /home/ubuntu/git/kani/src/kani-compiler/src/codegen_cprover_gotoc/compiler_interface.rs:72:35
  17: kani_compiler::codegen_cprover_gotoc::utils::debug::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::call_with_panic_debug_info::{{closure}}
             at /home/ubuntu/git/kani/src/kani-compiler/src/codegen_cprover_gotoc/utils/debug.rs:67:13
  18: std::thread::local::LocalKey<T>::try_with
             at /rustc/5f37001055c29982f4c27ee9edd90449c8e07774/library/std/src/thread/local.rs:442:16
  19: std::thread::local::LocalKey<T>::with
             at /rustc/5f37001055c29982f4c27ee9edd90449c8e07774/library/std/src/thread/local.rs:418:9
  20: kani_compiler::codegen_cprover_gotoc::utils::debug::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::call_with_panic_debug_info
             at /home/ubuntu/git/kani/src/kani-compiler/src/codegen_cprover_gotoc/utils/debug.rs:64:9
  21: <kani_compiler::codegen_cprover_gotoc::compiler_interface::GotocCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
             at /home/ubuntu/git/kani/src/kani-compiler/src/codegen_cprover_gotoc/compiler_interface.rs:71:25
  22: <rustc_session::session::Session>::time::<alloc::boxed::Box<dyn core::any::Any>, rustc_interface::passes::start_codegen::{closure#0}>
  23: <rustc_interface::passes::QueryContext>::enter::<<rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_errors::ErrorGuaranteed>>
  24: <rustc_interface::queries::Queries>::ongoing_codegen
  25: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorGuaranteed>>
  26: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
  27: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>
  28: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Kani unexpectedly panicked during compilation.
If you are seeing this message, please file an issue here: https://github.com/model-checking/kani/issues/new?labels=bug&template=bug_report.md

[Kani] current codegen item: declare_function: std::pin::Pin::<&'a mut T>::map_unchecked_mut
[Kani] current codegen location: Loc { file: "/home/ubuntu/.rustup/toolchains/nightly-2022-03-23-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/pin.rs", function: None, line: 788, col: Some(5) }
error: could not compile `tokio`
```

**Comment by zhassan-aws** [comment]
As of 7cc65683e9a, the panic now has this signature (omitting the rustc lines):
```
thread 'rustc' panicked at 'Expected self type to be a trait', kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs:924:21
stack backtrace:
   2: kani_compiler::codegen_cprover_gotoc::codegen::typ::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::codegen_dynamic_function_sig::{{closure}}
             at /home/ubuntu/git/kani/kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs:924:21
  10: kani_compiler::codegen_cprover_gotoc::codegen::typ::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::codegen_dynamic_function_sig
             at /home/ubuntu/git/kani/kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs:915:22
  11: kani_compiler::codegen_cprover_gotoc::codegen::typ::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::trait_method_vtable_field_type
             at /home/ubuntu/git/kani/kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs:299:21
  12: kani_compiler::codegen_cprover_gotoc::codegen::typ::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::trait_vtable_field_types::{{closure}}
             at /home/ubuntu/git/kani/kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs:424:34
  26: kani_compiler::codegen_cprover_gotoc::codegen::typ::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::trait_vtable_field_types
             at /home/ubuntu/git/kani/kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs:416:32
  27: kani_compiler::codegen_cprover_gotoc::codegen::typ::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::codegen_trait_vtable_type::{{closure}}
             at /home/ubuntu/git/kani/kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs:319:13
  28: kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx::ensure_struct
             at /home/ubuntu/git/kani/kani-compiler/src/codegen_cprover_gotoc/context/goto_ctx.rs:225:30
  29: kani_compiler::codegen_cprover_gotoc::codegen::typ::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::codegen_trait_vtable_type
             at /home/ubuntu/git/kani/kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs:318:9
  30: kani_compiler::codegen_cprover_gotoc::codegen::typ::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::codegen_fat_ptr
             at /home/ubuntu/git/kani/kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs:844:13
  31: kani_compiler::codegen_cprover_gotoc::codegen::typ::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::codegen_ty_ref
             at /home/ubuntu/git/kani/kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs:860:20
  32: kani_compiler::codegen_cprover_gotoc::codegen::typ::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::codegen_ty_inner
             at /home/ubuntu/git/kani/kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs:604:76
  33: kani_compiler::codegen_cprover_gotoc::codegen::typ::<impl kani_compiler::codegen_cprover_gotoc::context::goto_ctx::GotocCtx>::codegen_ty
             at /home/ubuntu/git/kani/kani-compiler/src/codegen_cprover_gotoc/codegen/typ.rs:537:24
```

**Comment by tedinski** [comment]
This suggests things are working now?

```
$ cargo new tokio-test
     Created binary (application) `tokio-test` package
$ cd tokio-test/
$ cargo add tokio --features full
    Updating crates.io index
      Adding tokio v1.20.1 to dependencies.
$ cargo kani
   Compiling libc v0.2.132
   Compiling proc-macro2 v1.0.43
   Compiling quote v1.0.21
   Compiling cfg-if v1.0.0
   Compiling unicode-ident v1.0.3
   Compiling log v0.4.17
   Compiling parking_lot_core v0.9.3
   Compiling syn v1.0.99
   Compiling smallvec v1.9.0
   Compiling memchr v2.5.0
   Compiling scopeguard v1.1.0
   Compiling once_cell v1.13.1
   Compiling bytes v1.2.1
   Compiling lock_api v0.4.7
   Compiling tokio v1.20.1
   Compiling socket2 v0.4.6
   Compiling num_cpus v1.13.1
   Compiling mio v0.8.4
   Compiling signal-hook-registry v1.4.0
   Compiling parking_lot v0.12.1
   Compiling tokio-macros v1.8.0
   Compiling tokio-test v0.1.0 (/home/ubuntu/experiments/specific_crate_failures/tokio-test)
    Finished dev [unoptimized + debuginfo] target(s) in 1m 00s
Error: No proof harnesses (functions with #[kani::proof]) were found to verify.
```

Perhaps we can close this one.

**Comment by zhassan-aws** [comment]
Confirmed. Closing it.
