### ISSUE TITLE
Kani throws a python exception if there is an error in the program

### ISSUE THREAD

**Issue by zhassan-aws** [model-checking/kani#830]
I tried this code:

```rust
fn main() {
    assert!(x);
}
```

using the following command line invocation:

```
kani triv.rs
```

with Kani version: `6dc03c2eb53`

I expected to see this happen:
```
error[E0425]: cannot find value `x` in this scope
 --> triv.rs:2:13
  |
2 |     assert!(x);
  |             ^ not found in this scope

```

Instead, this happened:
```
$ kani triv.rs 
Traceback (most recent call last):
  File "/home/ubuntu/git/kani/scripts/kani.py", line 197, in run_cmd
    returncode = cbmc_json_parser.transform_cbmc_output(stdout, output_style)
  File "/home/ubuntu/git/kani/scripts/cbmc_json_parser.py", line 121, in transform_cbmc_output
    raise Exception("CBMC Crashed - Unable to present Result")
Exception: CBMC Crashed - Unable to present Result

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/git/kani/scripts/kani", line 201, in <module>
    sys.exit(main())
  File "/home/ubuntu/git/kani/scripts/kani", line 59, in main
    if EXIT_CODE_SUCCESS != kani.compile_single_rust_file(args.input, base, symbol_table_json_filename, args):
  File "/home/ubuntu/git/kani/scripts/kani.py", line 261, in compile_single_rust_file
    return run_cmd(
  File "/home/ubuntu/git/kani/scripts/kani.py", line 199, in run_cmd
    raise Exception("JSON Parsing Error")
Exception: JSON Parsing Error
```
The CBMC json parser script should not be invoked if there was an error in compilation.

**Comment by zhassan-aws** [comment]
Kani also doesn't print the compile error even if the old format is specified:
```
$ kani --output-format old triv.rs 
Traceback (most recent call last):
  File "/home/ubuntu/git/kani/scripts/kani.py", line 197, in run_cmd
    returncode = cbmc_json_parser.transform_cbmc_output(stdout, output_style)
  File "/home/ubuntu/git/kani/scripts/cbmc_json_parser.py", line 121, in transform_cbmc_output
    raise Exception("CBMC Crashed - Unable to present Result")
Exception: CBMC Crashed - Unable to present Result

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/git/kani/scripts/kani", line 201, in <module>
    sys.exit(main())
  File "/home/ubuntu/git/kani/scripts/kani", line 59, in main
    if EXIT_CODE_SUCCESS != kani.compile_single_rust_file(args.input, base, symbol_table_json_filename, args):
  File "/home/ubuntu/git/kani/scripts/kani.py", line 261, in compile_single_rust_file
    return run_cmd(
  File "/home/ubuntu/git/kani/scripts/kani.py", line 199, in run_cmd
    raise Exception("JSON Parsing Error")
Exception: JSON Parsing Error
```
