### ISSUE TITLE
Some CBMC options only work with the old format

### ISSUE THREAD

**Issue by zhassan-aws** [model-checking/kani#921]
Some of the commonly-used CBMC options, e.g. `--show-properties` and `--trace` do not work unless `--output-format old` is specified.

Example:
```
$ cat trivial.rs 
fn main() {
    assert!(1 + 1 == 2);
}
$ kani trivial.rs --cbmc-args --show-properties
Traceback (most recent call last):
  File "/home/ubuntu/git/kani/scripts/cbmc_json_parser.py", line 665, in <module>
    main()
  File "/home/ubuntu/git/kani/scripts/cbmc_json_parser.py", line 72, in main
    return_code = transform_cbmc_output(sample_json_file_parsing, output_style=output_style)
  File "/home/ubuntu/git/kani/scripts/cbmc_json_parser.py", line 101, in transform_cbmc_output
    properties, messages = postprocess_results(properties)
  File "/home/ubuntu/git/kani/scripts/cbmc_json_parser.py", line 204, in postprocess_results
    has_reachable_unsupported_constructs = has_check_failure(properties, GlobalMessages.UNSUPPORTED_CONSTRUCT_DESC)
  File "/home/ubuntu/git/kani/scripts/cbmc_json_parser.py", line 237, in has_check_failure
    for property in properties:
TypeError: 'NoneType' object is not iterable
$ kani a.rs --output-format old  --cbmc-args --show-properties
CBMC version 5.50.0 (cbmc-5.50.0) 64-bit x86_64 linux
Reading GOTO program from file a.out
Generating GOTO Program
Adding CPROVER library (x86_64)
Removal of function pointers and virtual functions
Generic Property Instrumentation
Running with 16 object bits, 48 offset bits (user-specified)
Property main.assertion.1:
  file /home/ubuntu/examples/a.rs line 6 column 8 function main
  [KANI_REACHABILITY_CHECK] KANI_CHECK_ID_a.c64ace8a::a_0
  !TRUE

Property main.assertion.2:
  file /home/ubuntu/examples/a.rs line 6 column 8 function main
  [KANI_CHECK_ID_a.c64ace8a::a_0] attempt to add with overflow
  FALSE

Property <T as kani::Arbitrary>::any.assertion.1:
  file /home/ubuntu/git/kani/library/kani/src/arbitrary.rs line 17 column 5 function <T as kani::Arbitrary>::any
  resume instruction
  FALSE

Property pointer_primitives.1:
  
  dead object in OBJECT_SIZE(&temp_0)
  !(POINTER_OBJECT(&temp_0) == POINTER_OBJECT(__CPROVER_dead_object))

Property assertion.1:
  
  Code generation sanity check: Correct CBMC vtable size for StructTag("tag-_5528490532708175949") (MIR type Closure(DefId(2:9423 ~ std[c344]::rt::lang_start::{closure#0}), [(), i8, extern "rust-call" fn(()) -> i32, (fn(),)])). Please report failures:
https://github.com/model-checking/kani/issues/new?template=bug_report.md
  OBJECT_SIZE(&temp_0) == 8
```
With `--cbmc-args --trace`, the trace is not shown:
```
$ kani test.rs --cbmc-args --trace
CBMC 5.50.0 (cbmc-5.50.0)
CBMC version 5.50.0 (cbmc-5.50.0) 64-bit x86_64 linux
Reading GOTO program from file test.out
Generating GOTO Program
Adding CPROVER library (x86_64)
Removal of function pointers and virtual functions
Generic Property Instrumentation
Running with 16 object bits, 48 offset bits (user-specified)
Starting Bounded Model Checking
Runtime Symex: 0.00107007s
size of program expression: 78 steps
simple slicing removed 3 assignments
Generated 4 VCC(s), 2 remaining after simplification
Runtime Postprocess Equation: 1.758e-05s
Passing problem to propositional reduction
converting SSA
Runtime Convert SSA: 0.000194534s
Running propositional reduction
Post-processing
Runtime Post-process: 2.81e-05s
Solving with MiniSAT 2.2.1 with simplifier
132 variables, 33 clauses
SAT checker: instance is SATISFIABLE
Runtime Solver: 0.000103452s
Runtime decision procedure: 0.000338317s

RESULTS:
Check 1: main.assertion.2
         - Status: FAILURE
         - Description: "assertion failed: x != 0"

Check 2: assertion.1
         - Status: SUCCESS
         - Description: "Code generation sanity check: Correct CBMC vtable size for StructTag("tag-_5528490532708175949") (MIR type Closure(DefId(2:9423 ~ std[c344]::rt::lang_start::{closure#0}), [(), i8, extern "rust-call" fn(()) -> i32, (fn(),)])). Please report failures:
https://github.com/model-checking/kani/issues/new?template=bug_report.md"

Check 3: pointer_primitives.1
         - Status: SUCCESS
         - Description: "pointer to dead object"


SUMMARY: 
 ** 1 of 3 failed
Failed Checks: assertion failed: x != 0
 File: "/home/ubuntu/examples/fails/test.rs", line 3, in main

VERIFICATION:- FAILED
```

**Comment by feliperodri** [comment]
CBMC output is now parsed natively in Rust (cbmc_output_parser.rs). The `--show-properties` and `--trace` options work with the current parser.
